/**
 * Hand-authored PlannerMusicPlan variants for diversity review.
 * Used to verify mapToGeneratorPlan does not collapse distinct intents.
 */

import type { PlannerMusicPlan } from '../schema';
import { clampMusicPlan } from '../schema';

export const DIVERSITY_PROMPTS = [
  'dark cinematic boss battle',
  'calm reflective piano',
  'playful retro game loop',
  'dreamy ambient floating pad',
  'tense stealth pulse',
] as const;

const BASE = {
  phraseBars: 2,
  totalBars: 8,
  rhythmDensity: 0.5,
  restDensity: 0.2,
  syncopation: 0.35,
  harmonicComplexity: 0.45,
  repetition: 0.55,
  variation: 0.45,
  consonance: 0.7,
  leapRate: 0.35,
  motifShape: 'undulating',
  articulation: 'legato',
  dynamics: 'medium',
  notes: [] as string[],
};

export const DIVERSITY_PLANNER_PLANS: Record<(typeof DIVERSITY_PROMPTS)[number], PlannerMusicPlan> = {
  'dark cinematic boss battle': clampMusicPlan({
    ...BASE,
    prompt: 'dark cinematic boss battle',
    style: 'cinematic orchestral action',
    mood: ['dark', 'tense', 'epic'],
    tempoBpm: 148,
    meter: '4/4',
    keyCenter: 'D',
    scaleType: 'minor',
    rhythmDensity: 0.72,
    restDensity: 0.12,
    syncopation: 0.58,
    harmonicComplexity: 0.68,
    repetition: 0.7,
    variation: 0.35,
    consonance: 0.55,
    melodicRange: { min: 'D3', max: 'D5' },
    leapRate: 0.45,
    dynamics: 'loud',
    texture: 'melody+chords',
    registerBias: 'wide',
    percussionEnergy: 0.82,
  }),
  'calm reflective piano': clampMusicPlan({
    ...BASE,
    prompt: 'calm reflective piano',
    style: 'solo piano ambient',
    mood: ['calm', 'reflective', 'gentle'],
    tempoBpm: 68,
    meter: '3/4',
    keyCenter: 'G',
    scaleType: 'major',
    rhythmDensity: 0.32,
    restDensity: 0.42,
    syncopation: 0.12,
    harmonicComplexity: 0.28,
    repetition: 0.45,
    variation: 0.38,
    consonance: 0.88,
    melodicRange: { min: 'G3', max: 'B5' },
    leapRate: 0.18,
    articulation: 'legato',
    dynamics: 'soft',
    texture: 'monophonic',
    registerBias: 'mid',
    percussionEnergy: 0.08,
  }),
  'playful retro game loop': clampMusicPlan({
    ...BASE,
    prompt: 'playful retro game loop',
    style: 'chiptune retro game',
    mood: ['playful', 'bright', 'bouncy'],
    tempoBpm: 128,
    meter: '4/4',
    keyCenter: 'C',
    scaleType: 'major',
    rhythmDensity: 0.78,
    restDensity: 0.08,
    syncopation: 0.42,
    harmonicComplexity: 0.35,
    repetition: 0.78,
    variation: 0.28,
    consonance: 0.82,
    melodicRange: { min: 'C4', max: 'C6' },
    leapRate: 0.52,
    motifShape: 'ascending',
    dynamics: 'medium',
    texture: 'melody+bass',
    registerBias: 'high',
    percussionEnergy: 0.55,
  }),
  'dreamy ambient floating pad': clampMusicPlan({
    ...BASE,
    prompt: 'dreamy ambient floating pad',
    style: 'ambient pad drone',
    mood: ['dreamy', 'floating', 'ethereal'],
    tempoBpm: 72,
    meter: '6/8',
    keyCenter: 'A',
    scaleType: 'dorian',
    rhythmDensity: 0.22,
    restDensity: 0.55,
    syncopation: 0.18,
    harmonicComplexity: 0.4,
    repetition: 0.82,
    variation: 0.15,
    consonance: 0.75,
    melodicRange: { min: 'A3', max: 'E5' },
    leapRate: 0.12,
    motifShape: 'static',
    articulation: 'legato',
    dynamics: 'soft',
    texture: 'monophonic',
    registerBias: 'wide',
    percussionEnergy: 0.05,
  }),
  'tense stealth pulse': clampMusicPlan({
    ...BASE,
    prompt: 'tense stealth pulse',
    style: 'minimal electronic thriller',
    mood: ['tense', 'stealthy', 'dark'],
    tempoBpm: 96,
    meter: '2/4',
    keyCenter: 'F#',
    scaleType: 'phrygian',
    rhythmDensity: 0.55,
    restDensity: 0.35,
    syncopation: 0.72,
    harmonicComplexity: 0.5,
    repetition: 0.62,
    variation: 0.48,
    consonance: 0.42,
    melodicRange: { min: 'F#2', max: 'C4' },
    leapRate: 0.22,
    motifShape: 'descending',
    dynamics: 'medium',
    texture: 'melody+bass',
    registerBias: 'low',
    percussionEnergy: 0.65,
  }),
};
