export const MOCK_PLANNER_PLAN_RAW = {
  prompt: 'dark cinematic floating strings, 8 bars',
  style: 'cinematic ambient orchestral',
  mood: ['dark', 'floating', 'tense'],
  tempoBpm: 92,
  meter: '4/4',
  keyCenter: 'D',
  scaleType: 'natural minor',
  phraseBars: 2,
  totalBars: 8,
  rhythmDensity: 0.42,
  restDensity: 0.35,
  syncopation: 0.28,
  harmonicComplexity: 0.55,
  repetition: 0.62,
  variation: 0.38,
  consonance: 0.72,
  melodicRange: { min: 'D3', max: 'A5' },
  leapRate: 0.3,
  motifShape: 'undulating',
  articulation: 'legato',
  dynamics: 'soft',
  texture: 'melody+chords',
  registerBias: 'wide',
  percussionEnergy: 0.2,
  notes: [],
} as const;
